apiVersion: scripting.sitewhere.io/v1alpha4
kind: SiteWhereScriptTemplate
metadata:
  name: command-delivery-command-encoder
  labels:
    sitewhere.io/functional-area: command-delivery
    scripting.sitewhere.io/category: command-delivery-command-encoder-category
spec:
  name: Command Encoder
  description: Performs custom device-specific command encoding.
  interpreterType: js
  script: |
    // Available variable bindings:
    // ----------------------------
    // execution: (IDeviceCommandExecution) Command execution information.
    // nesting: (IDeviceNestingContext) Device information including nesting details.
    // assignment: (IDeviceAssignment) Assignment associated with invocation event.
    // logger: (Logger) Supports output to system logs.
    // ----------------------------
    // return value (byte[]): Binary output sent to transport.
    // ----------------------------
    
    logger.info 'Building command execution...'
    
    if (execution.command.name == 'serialPrintln') {
        def message = execution.parameters['message']
        logger.info "Attempting serial println with message '" + message + "'"
        return (new String("{'command': 'print', 'message': '" + message + "'}")).getBytes()
    }
    
    return (new String("{'command': 'unknown'}")).getBytes()
