apiVersion: scripting.sitewhere.io/v1alpha4
kind: SiteWhereScriptTemplate
metadata:
  name: outbound-connectors-uri-builder
  labels:
    sitewhere.io/functional-area: outbound-connectors
    scripting.sitewhere.io/category: outbound-connectors-uri-builder-category
spec:
  name: URI Builder
  description: Implements a URI builder.
  interpreterType: js
  script: |
    // Available variable bindings:
    // ----------------------------
    // context: (IDeviceEventContext) Context information associated with device event.
    // event: (IDeviceEvent) Current device event being processed by connector.
    // assignment: (IDeviceAssignment) Assignment associated with invocation event.
    // device: (IDevice) Information about device related to event.
    // logger: (Logger) Supports output to system logs.
    // ----------------------------
    // return value (String): URI
    // ----------------------------
    
    String uri = String.format("http://httpbin.org/anything/%s", device.getToken())
    logger.info String.format("HTTP connector using URI: %s", uri)
    return uri
